k-DOP implementation
WANNABY/math pull request #9
Opened 2023-11-24 14:50 UTC by allcreater

A convex polytope that is a generalization of AABB with N axises.

Right now only 14-DOP is supported (a cube with 8 additional planes that cutting vertices), but the code is pretty general

2023-11-27 13:32 UTC, Hagartinger requested changes

2023-11-27 13:32 UTC, Hagartinger commented on include/math/utils/ndop.h
> +//template <auto Traits>
```suggestion
};
```

2023-11-27 13:32 UTC, Hagartinger commented on include/math/utils/ndop.h
> +class DOP : DOP14_Traits {
I'm not sure if DOP is a widely known abbreviation (it wasn't for me until today :-) ) 
Consider renaming to a more verbose DiscreteOrientedPolytope, or at least leave a comment nearby.

2023-11-27 13:32 UTC, Hagartinger commented on include/math/utils/ndop.h
> +        }()
Let's move it into constructor, since the initialisation is not trivial.

2023-11-27 13:32 UTC, Hagartinger commented on include/math/utils/ndop.h
> +    constexpr size_t get_inverse_plane_index(size_t index) const noexcept {
I think that's confusing that we work with indecies. That's hard to tell by look which `index` corresponds to what. I suggest giving each axis/plane a label and work with labels instead.

2023-11-27 13:32 UTC, Hagartinger commented on include/math/utils/ndop.h
> +    constexpr static DOP compute(
Why not a constructor?

2023-11-27 13:32 UTC, Hagartinger commented on include/math/utils/ndop.h
> +    std::vector<math::float3> get_points() const noexcept;
Do we need it in public interface? 
Also it seems that std::array could be used instead, to save on heap allocations

2023-11-27 13:32 UTC, Hagartinger commented on include/math/utils/ndop.h
> +    return std::any_of(std::begin(distances_), std::end(distances_), [](const auto& d) { return d <= std::numeric_limits<float>::lowest(); });
I think it could result in a false-positive if a DOP was created from points lying on a plane/line.

2023-11-27 13:32 UTC, Hagartinger commented on include/math/utils/ndop.h
> +        const auto dot = math::dot(point, get_plane_normal(i));
```suggestion
        const auto projection = math::dot(point, get_plane_normal(i));
```
`dot` doesn't describe your intent. Feel free to change it to something more verbose if you want.

2023-11-27 13:32 UTC, Hagartinger commented on include/math/utils/ndop.h
> +        if ( dot > distances_[i] + 1e-7) {
I would move implementation code into separate cpp file and replaced magic variable with a constexpr constant

2023-11-27 13:32 UTC, Hagartinger commented on include/math/utils/ndop.h
> +        if ( dot > distances_[i] + 1e-7) {
Also it seems that empty DOP needs separate consideration

2023-11-27 13:32 UTC, Hagartinger commented on include/math/utils/ndop.h
> +                }
Consider adding this functionality to the matrix class instead

2023-11-27 13:32 UTC, Hagartinger commented on include/math/utils/ndop.h
> +    static const auto planes_adjacency = [](){
Why can't it be calculated at compile time?

2023-11-27 14:20 UTC, allcreater commented on include/math/utils/ndop.h
> +    static const auto planes_adjacency = [](){
technically it can, but requires more complicated code for deducing std::array size... 
and also array's actual size could be less than that number, because some intersection points could be discarded

2023-11-28 06:52 UTC, Hagartinger commented on include/math/utils/ndop.h
> +    return std::any_of(std::begin(distances_), std::end(distances_), [](const auto& d) { return d <= std::numeric_limits<float>::lowest(); });
Nah it should be fine

2023-11-28 06:55 UTC, Hagartinger commented on include/math/utils/ndop.h
> +        if ( dot > distances_[i] + 1e-7) {
On the second thought it should be fine for empty DOP as well

2023-11-30 09:05 UTC, allcreater commented on include/math/utils/ndop.h
> +    constexpr static DOP compute(
to leave API consistent with AABB and bounding sphere :)

2023-11-30 10:27 UTC, Hagartinger approved these changes

2023-11-30 10:56 UTC, merged